# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Setting

# Model Form Field configuration
form: $/power2all/multisite/models/setting/fields.yaml

# Model Class name
modelClass: Power2all\Multisite\Models\Setting

# Default redirect location
defaultRedirect: power2all/multisite/settings

# Create page
create:
    title: power2all.multisite::lang.controller.create
    redirect: power2all/multisite/settings/update/:id
    redirectClose: power2all/multisite/settings

# Update page
update:
    title: power2all.multisite::lang.controller.create
    redirect: power2all/multisite/settings
    redirectClose: power2all/multisite/settings
